import Navigation from "@/components/Navigation/Navigation.jsx";
import "../style/globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "@/components/Footer/Footer.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="flex flex-col h-screen">
        <Navigation />
        <div className="flex-1">{children}</div>
        <Footer />
        <ToastContainer position="bottom-right" />
      </body>
    </html>
  );
}
